import { NumberFormatStyle } from "@angular/common";

export class FormParam {
    //3040
    START_DATE: Date;
    END_DATE: Date;
    P_ST_DATE: Date;
    P_END_DATE: Date;
    POST_DATE: Date;
    START_PREPARE_DATE: Date;
    END_PREPARE_DATE: Date;
    CHECK_DATE: Date;
    START_MONTH: Date;
    END_MONTH: Date;
    GL_PROVISION_POST_DATE: Date;

    START_DATE1: any;
    START_DATE2: any;
    START_DATE3: any;
    START_DATE4: any;
    START_DATE5: any;
    START_DATE6: any;
    START_DATE7: any;
    START_DATE8: any;

    END_DATE1: any;
    END_DATE2: any;
    END_DATE3: any;
    END_DATE4: any;
    END_DATE5: any;
    END_DATE6: any;
    END_DATE7: any;
    END_DATE8: any;
    NATURE_NO: any;
    RP_NAME: any;



    ALL?: any;
    ALL_REQ?: any;
    UN_RECONCILED?: string;
    AS_ON: number;
    AS_ON1: string;
    AMOUNT: any;
    PERIODIC: number;
    PERIODIC1: string;
    NUMERIC: string;
    REPORT_OPTION_ALL: number;
    REPORT_OPTION_ACTIVE: number;
    REPORT_OPTION_INACTIVE: number;
    REPORT_OPTION_REPORTXLS: number;
    CHEQUE_GIVEN: string;
    CHEQUE_RECEIVE
    COST_NO?: any;
    BU_NO?: any;
    FUND?: any;
    OPENING?: any;
    OPENIN_DETAILS?: any;
    OPENING_TRANSECTION?: any;
    TRANSECTION?: any;
    SINGLE_REPORT_TYPE?: any;
    REPORT_TYPE_3040?: string;
    DETAILS_REPORT_TYPE?: string;
    REP_CATEGORY?: any;
    REPORT_FORMAT_LIST?: any;
    POSTING?: any;
    POSTING_STATUS?: any;
    POSTING_DATE?: any;
    COMPANY_TYPE?: any;
    NOT_POSTING?: any;
    BA?: any;
    BA_M?: any;
    BA_NO?: any;
    BUDGET_BALANCE_INFO?: any;
    BUDGET_GENERAL_LEDGER?: any;
    VTYPE_NO?: any;
    VTYPE_NO2: number;
    V_NO?: any;
    PRINT_TYPE?: any;
    REQ_BY_NAME?: any;
    REPORT_OUTPUT_FORMATE?: any;
    MULTICURRENCY_NUMBER?: any;
    ACC_NO?: any;
    ACC_NO1?: any;
    S_AC_NO?: any;
    RADIO_4220?: any;
    DEFAULT?: string;
    WITHOUTCOSTCENTER?: string;
    VOUCHERLIST?: string;
    WITHCASHBANK?: string;
    YES_APPROVED_STATUS?: any;
    NO_APPROVED_STATUS?: any;
    APPROVED_STATUS?: any;
    CHECK_STATUS?: any;
    PAY_SCHEDULE_STATUS?: any;
    MONEYREQ_NO?: any;
    BILL_NO?: any;
    STATUS_NO?: any;
    ADJUST_VALUE?: any;
    NEXT_STATUS_NO?: any;
    APPSET_NO?: any;
    APPROVE_BY?: any;
    APPROVE_DATE?: any;
    APPROVE_FLAG?: any;
    MONEYADJUST_NO?: any;
    MONEYADJUST_DATE?: any;
    MONEYSCHEDULE_NO?: any;

    STAT?: any;
    UNCHECK_STATUS?: any;
    TRANSCATION_DATE?: any;
    APPROVAL_DATE?: any;
    ACC_CODE?: any;
    ACC_NAME?: any;
    POSTING_TYPE?: any;
    POSTING_ON?: any;
    REF_NO?: any;
    LANDSCPAE?: any;
    REPORT_OPTION: number;
    WITHDESCRIPTION?: any;
    SHOWRUNNINGBALANCE?: any;
    GROUPLEDGERREPORT?: any;
    G_USER_NO?: any;
    MONTHLYLEDGERREPORT?: any;
    MONTHLYSTATEMENT?: any;
    BASECURRENCY?: string;
    MULTICURRENCY?: string;
    COST?: string;
    GROUP_COST?: string;
    IS_COST_GROUP?: string;
    IS_REPORT_TYPE?: any;
    IS_CURRENCY_TYPE?: string;
    GENERAL_CATEGORY?: string;
    COMPARISON_CATEGORY?: string;
    IS_CHECKED?: any;
    IS_UNCHECKED?: any;
    IS_CTRL_CHECKED?: any;
    IS_CTRL_UNCHECKED?: any;
    EMP_NO?: any;
    V_ID?: any;
    ACTIVE_NO?: any;
    SUMMARY_TYPE?: string;
    SUMMARY_REPORT_TYPE?: string;
    SUMMARY_REPORT_DETAILS?: string;
    IREPORT_TYPE?: string;
    GENERAL_REPORT_TYPE?: string;
    COMPARISON_REPORT_TYPE?: string;
    BRANCH_NAME: string;
    OWN_REQUISITION_ONLY?: any;
    IS_SHOW_YES?: any;
    IS_SHOW_NO?: any;
    REQ_FROM?: any;
    IS_SHOW_TYPE?: any;
    S_ACC_NO?: any;
    CHEQUE?: any;
    BANK?: any;
    R_TYPE?: any;
    BANKDTL_NO?: any;
    RP_NO?: any;
    BANK_NO?: any;
    BANK_NO1?: any;
    LIST?: string;
    DATE_WISE?: string;
    COST_CENTER_WISE?: string;
    BA_WISE?: string;
    GROUP?: string;
    PAY_TO_ACC_NO?: any;
    BILL_STATUS: string;
    MONEYSCHEDULE_ID: string;
    MONEYREQ_ID: string;
    MONEYADJUST_ID: string;
    PAYMENT_TYPE: string;

    REP_TYPE: string;
    SERVER_NAME: string;
    FORMAT_SHORT_NAME: string;
    SS_CREATOR: string;// Prepared By
    CURRENCY_TYPE: string;
    SIDE_GROUP_LADER: string;
    SIDE_MOUNTH_STATE: string;
    POST_STATUS: string;
    COST_TYPE: string;
    CATEGORY: string;
    SHOW_TYPE: string;
    DATE: string;
    IS_CATEGORY: string;
    PREPARED_BY: any;
    CHECK_BY_NAME: string;
    REPORT_TYPE: string;
    FLAT: string;
    TREE: string;
    MODULE: string;
    TASK_NAME: string;
    TYPE_NAME: string;
    APPSETDTL_NO:number;
    CHECKBOOK_ID?: string;
    MULTIPLE_CODE: string;




    IS_COST_CENTER_ALL: boolean;
    IS_BUSINESS_AREA_ALL: boolean;
    IS_SHOW_DETAIL: boolean;
    CHECKED_ALL: any;
    SHOW_DETAIL: any;
    IS_SUPPRESS_ZERO: boolean;
    IS_CHECKED_ALL_COMPANY: boolean;
    IS_SHOW_PAY: boolean;
    IS_SHOW_PARTICULAR_QUS: boolean;
    IS_SHOW_REC: boolean;
    IS_REF_NO_ALL: boolean;
    IS_SUMMARY_FLAG: boolean;
    IS_OPENING: boolean;
    IS_CHEQUE_DATE: boolean;
    IS_PREPARE_DATE: boolean;
    IS_SHOW_BUDGET: boolean;
    IS_SHOW_BALANCE: boolean;
    CTRL_SHOWPATH: boolean;
    IS_COST_CENTER_INCOMPLETE: boolean;
    BANK_ACC_NO?: any;
    PAY_TO_NAME: any;
    LEDGER_HEAD: any;
    PAY_TO_ACC_NO1: any;
    CHECK_NO: any;
    FILTER_OPTION: any;
    SETTLEMENT_TYPE: any;
    COMPANY_NO: any;
    REGESTER: any;
    RD_REPORT_TYPE: any;
    DATE_OPTIONS: any;
    DAILY: any;
    MONTHLY: any;
    REPORT_NAME: any;
    FY: any;
    PERIOD_NO: any;
    PERIOD_NAME: any;
    BUDGET_PERIOD_NO: any;
    BUDGET_ID: any;
    T_STYLE: any;
    SUMMARY: any;
    DETAILS: any;
    NORMAL: any;
    VARIANCE: any;
    RADIO_4000: any;
    POSTED: any;
    UNPOSTED: any;
    TRANSACTION_DATE_TYPE: any;
    APPROVE_DATE_TYPE: any;
    RG_GROUP_LEDGER: string;
    IS_GROUP_LEGERD_COMPANY_WISE: boolean;
    IS_GROUP_LEGERD_GROUP: boolean;
    EXCLE: boolean;
    WATING: number;
    APPROVE: number;
    DENY: number;
    ACCEPT: number;
    UOM_NO: number;
    MONEYREQ_QTY: number;
    UNACCEPT: number;
    QJ_NO: any;
    SEARCH_NAME: string;
    RECONCILED: any;
    BUDGET_STATUS: number;
    SUBMENU_ID: string;
    SUBMENU_ID2: string;
    INVOICE: string;
    NEGOTIATION: string;
    REALIZATION: string;
    CUSTOMER_NAME: string;
    CUSTOMER_NO: any;
    LC_NO: any;
    SALESCONTRACT_NO: any;   
    TRN_LIST: any;  
    MONEYPAY_NO: any;  
    BILLDATE: string;
    ALL1: string;
    SI_LOCAL: string;
    PI_EXPORT: string;
    CI_EXPORT: string;
    EXPORT_STATUS: string;
    ACCOUNT_NOT_MAP: number;
    COST_NOT_MAP: number;
    SUPPLIER_NOT_MAP: number;
    APPROVED_QTY: number;
    TOTAL_AMT: number;
    TOTAL_JOB_GROUP: number
    SELECTED: string;
    CUSTOMER_NOT_MAP: number;
    WO_NO: number;
    STATUS: any;
    FORM_ID: string;
    FROM_BU_NAME: string;
    PERMANENT: string;
    PRESENT: string;
    QJ_NAME: string;
    TRAN_ID: string;
    START_BANK_DATE: Date;
    END_BANK_DATE: Date;
    FLAG_CHK: number;
    COST_NAME: string;
    BU_NAME: string;
    NOTE: string;
    CUR_NAME: string;
    PARTICULAR_NO: number;
    RATE: number;
    PAID: any;
    PENDING: any;
    RADIO_BUTTON_TYPE: any;
    PAYMENT_TYPE_OPTION: any;
    EMP_NAME: any;
    CUR_NO: any;
    SUPPLIER_NO: any;
    PAY_NO: any;
    PAY_ID: any;
    REQ_BY: any;
    PAY_ALL: any;
    CASH: Number

    
    constructor(options: any = {}) {

        this.PAID = options.PAID || null;
        this.CASH = options.CASH || null;

        this.G_USER_NO = options.G_USER_NO || null;
        this.WO_NO = options.WO_NO || null;
        this.MONEYREQ_QTY = options.MONEYREQ_QTY || null;
        this.TOTAL_AMT = options.TOTAL_AMT || null;
        this.APPROVED_QTY = options.APPROVED_QTY || null;
        this.UOM_NO = options.UOM_NO || null;
        this.PENDING = options.PENDING || null;
        this.PARTICULAR_NO = options.PARTICULAR_NO || null;
        this.RATE = options.RATE || null;
        this.RADIO_BUTTON_TYPE = options.RADIO_BUTTON_TYPE || null;
        this.PAYMENT_TYPE_OPTION = options.PAYMENT_TYPE_OPTION || null;
        this.COST_NAME = options.COST_NAME || '';
        this.FROM_BU_NAME = options.FROM_BU_NAME || '';
        this.NOTE = options.NOTE || '';
        this.FLAG_CHK = options.FLAG_CHK || 0;
        this.QJ_NAME = options.QJ_NAME || '';
        this.TRAN_ID = options.TRAN_ID || '';
        this.EMP_NAME = options.EMP_NAME || '';
        this.CUR_NAME = options.CUR_NAME || '';
        this.START_BANK_DATE = options.START_BANK_DATE || new Date();
        this.END_BANK_DATE = options.END_BANK_DATE || new Date();
        this.START_DATE = options.START_DATE || new Date();
        this.P_END_DATE = options.P_END_DATE || new Date();
        this.P_ST_DATE = options.P_ST_DATE || new Date();
        this.P_ST_DATE = options.P_ST_DATE || new Date();
        this.END_DATE = options.END_DATE || new Date();
        this.POST_DATE = options.POST_DATE || null;
        this.REQ_BY = options.REQ_BY || null;
        this.CHECK_DATE = options.CHECK_DATE || new Date();
        this.START_PREPARE_DATE = options.START_PREPARE_DATE || new Date();
        this.END_PREPARE_DATE = options.END_PREPARE_DATE || new Date();
        this.START_MONTH = options.START_MONTH || new Date();
        this.END_MONTH = options.END_MONTH || new Date();
        this.GL_PROVISION_POST_DATE = options.GL_PROVISION_POST_DATE || new Date();

        this.ACCOUNT_NOT_MAP = options.ACCOUNT_NOT_MAP || null;
        this.SUPPLIER_NO = options.SUPPLIER_NO || null;
        this.COST_NOT_MAP = options.COST_NOT_MAP || null;
        this.EXPORT_STATUS = options.EXPORT_STATUS || null;
        this.ALL1 = options.ALL1 || null;
        this.CUR_NO = options.CUR_NO || null;
        this.SI_LOCAL = options.SI_LOCAL || null;
        this.PERMANENT = options.PERMANENT || null;
        this.PRESENT = options.PRESENT || null;
        this.PI_EXPORT = options.PI_EXPORT || null;
        this.CI_EXPORT = options.CI_EXPORT || null;
        this.NUMERIC = options.NUMERIC || null;
        this.POSTING = options.POSTING || null;
        this.NOT_POSTING = options.NOT_POSTING || null;
        this.NORMAL = options.NORMAL || null;
        this.LIST = options.LIST || null;
        this.DATE_WISE = options.DATE_WISE || null;
        this.COST_CENTER_WISE = options.COST_CENTER_WISE || null;
        this.BA_WISE = options.BA_WISE || null;
        this.VARIANCE = options.VARIANCE || null;
        this.ALL = options.ALL || null;
        this.FUND = options.FUND || null;
        this.ADJUST_VALUE = options.ADJUST_VALUE || null;
        this.UN_RECONCILED = options.UN_RECONCILED || null;
        this.COST_NO = options.COST_NO || null;
        this.BU_NO = options.BU_NO || null;
        this.BA = options.BA || null;
        this.BA_M = options.BA_M || null;
        this.REQ_FROM = options.REQ_FROM || '';
        this.BILL_STATUS = options.BILL_STATUS || null;
        this.BUDGET_BALANCE_INFO = options.BUDGET_BALANCE_INFO || null;
        this.BUDGET_GENERAL_LEDGER = options.BUDGET_GENERAL_LEDGER || null;
        this.OPENING = options.OPENING || null;
        this.OPENIN_DETAILS = options.OPENIN_DETAILS || null;
        this.OPENING_TRANSECTION = options.OPENING_TRANSECTION || null;
        this.TRANSECTION = options.TRANSECTION || null;
        this.SINGLE_REPORT_TYPE = options.SINGLE_REPORT_TYPE || null;
        this.DETAILS_REPORT_TYPE = options.DETAILS_REPORT_TYPE || null;
        this.REP_CATEGORY = options.REP_CATEGORY || null;
        this.POSTING_STATUS = options.POSTING_STATUS || null;
        this.POSTING_DATE = options.POSTING_DATE || null;
        this.COMPANY_TYPE = options.COMPANY_TYPE || null;
        this.POSTING = options.POSTING || null;
        this.NOT_POSTING = options.NOT_POSTING || null;
        this.RADIO_4220 = options.RADIO_4220 || null;
        this.RD_REPORT_TYPE = options.RD_REPORT_TYPE || null;
        this.BA_NO = options.BA_NO || 0;
        this.VTYPE_NO = options.VTYPE_NO || '';
        this.VTYPE_NO = options.VTYPE_NO || '';
        this.BU_NAME = options.BU_NAME || '';
        this.V_NO = options.V_NO || '';
        this.MONEYSCHEDULE_ID = options.MONEYSCHEDULE_ID || '';
        this.MONEYREQ_ID = options.MONEYREQ_ID || '';
        this.MONEYADJUST_ID = options.MONEYADJUST_ID || '';
        this.PRINT_TYPE = options.PRINT_TYPE || '';
        this.REPORT_OUTPUT_FORMATE = options.REPORT_OUTPUT_FORMATE || '';
        this.MULTICURRENCY_NUMBER = options.MULTICURRENCY_NUMBER || '';
        this.REPORT_NAME = options.REPORT_NAME || '';
        this.CHECKBOOK_ID = options.CHECKBOOK_ID || '';
        this.CHEQUE_GIVEN = options.CHEQUE_GIVEN || '';
        this.REQ_BY_NAME = options.REQ_BY_NAME || '';
        this.CHEQUE_RECEIVE = options.CHEQUE_RECEIVE || '';
        this.ACC_NO = options.ACC_NO || '';
        this.ACC_NO1 = options.ACC_NO1 || '';
        this.S_AC_NO = options.S_AC_NO || '';
        this.DEFAULT = options.DEFAULT || '';
        this.WITHOUTCOSTCENTER = options.WITHOUTCOSTCENTER || '';
        this.VOUCHERLIST = options.VOUCHERLIST || '';
        this.WITHCASHBANK = options.WITHCASHBANK || '';
        this.YES_APPROVED_STATUS = options.YES_APPROVED_STATUS || '';
        this.NO_APPROVED_STATUS = options.NO_APPROVED_STATUS || '';
        this.CHECK_STATUS = options.CHECK_STATUS || '';
        this.FILTER_OPTION = options.FILTER_OPTION || '';
        this.UNCHECK_STATUS = options.UNCHECK_STATUS || '';
        this.TRANSCATION_DATE = options.TRANSCATION_DATE || '';
        this.BRANCH_NAME = options.BRANCH_NAME || '';
        this.APPROVAL_DATE = options.APPROVAL_DATE || '';
        this.ACC_CODE = options.ACC_CODE || '';
        this.ACC_NAME = options.ACC_NAME || '';
        this.POSTING_TYPE = options.POSTING_TYPE || '';
        this.PERIODIC1 = options.PERIODIC1 || '';
        this.RG_GROUP_LEDGER = options.RG_GROUP_LEDGER || '';
        this.REF_NO = options.REF_NO || '';
        this.FY = options.FY || '';
        this.AS_ON1 = options.AS_ON1 || '';
        this.PERIOD_NO = options.PERIOD_NO || '';
        this.PAYMENT_TYPE = options.PAYMENT_TYPE || '';
        this.LANDSCPAE = options.LANDSCPAE || '';
        this.WITHDESCRIPTION = options.WITHDESCRIPTION || '';
        this.SHOWRUNNINGBALANCE = options.SHOWRUNNINGBALANCE || '';
        this.GROUPLEDGERREPORT = options.GROUPLEDGERREPORT || '';
        this.GROUP = options.GROUP || '';
        this.MONTHLYLEDGERREPORT = options.MONTHLYLEDGERREPORT || '';
        this.MONTHLYSTATEMENT = options.MONTHLYSTATEMENT || '';
        this.BASECURRENCY = options.BASECURRENCY || '';
        this.MULTICURRENCY = options.MULTICURRENCY || '';
        this.COST = options.COST || '';
        this.GROUP_COST = options.GROUP_COST || '';
        this.IS_REPORT_TYPE = options.IS_REPORT_TYPE || '';
        this.IS_CURRENCY_TYPE = options.IS_CURRENCY_TYPE || '';
        this.GENERAL_CATEGORY = options.GENERAL_CATEGORY || '';
        this.COMPARISON_CATEGORY = options.COMPARISON_CATEGORY || '';
        this.SETTLEMENT_TYPE = options.SETTLEMENT_TYPE || '';
        this.DAILY = options.DAILY || '';
        this.MONTHLY = options.MONTHLY || '';
        this.CHECK_NO = options.CHECK_NO || '';
        this.LEDGER_HEAD = options.LEDGER_HEAD || '';
        this.SEARCH_NAME = options.SEARCH_NAME || '';
        this.RP_NAME = options.RP_NAME || '';
        this.IS_CHECKED = options.IS_CHECKED || 0;
        this.IS_UNCHECKED = options.IS_UNCHECKED || 0;
        this.APPROVED_STATUS = options.APPROVED_STATUS || 0;
        this.RP_NO = options.RP_NO || 0;
        this.BANK_NO = options.BANK_NO || 0;
        this.BANK_NO1 = options.BANK_NO1 || 0;
        this.PAY_TO_ACC_NO = options.PAY_TO_ACC_NO || 0;
        this.PAY_TO_ACC_NO1 = options.PAY_TO_ACC_NO1 || 0;
        this.COMPANY_NO = options.COMPANY_NO || '';
        this.BUDGET_ID = options.BUDGET_ID || '';

        this.IS_CTRL_CHECKED = options.IS_CTRL_CHECKED ||null;
        this.IS_CTRL_UNCHECKED = options.IS_CTRL_UNCHECKED ||null;
        this.POSTING_ON = options.POSTING_ON ||null;
        this.POSTED = options.POSTED ||null;
        this.UNPOSTED = options.UNPOSTED ||null;
        this.NATURE_NO = options.NATURE_NO ||null;
        this.ACTIVE_NO = options.ACTIVE_NO || null;
        this.BANKDTL_NO = options.BANKDTL_NO ||null;
        this.BANK_ACC_NO = options.BANK_ACC_NO ||null;
        this.DATE_OPTIONS = options.DATE_OPTIONS ||null;
        this.BUDGET_PERIOD_NO = options.BUDGET_PERIOD_NO ||null;
        this.T_STYLE = options.T_STYLE ||null;
        this.SUMMARY = options.SUMMARY ||null;
        this.DETAILS = options.DETAILS ||null;
        this.RADIO_4000 = options.RADIO_4000 ||null;

        this.AMOUNT = options.AMOUNT || '';
        this.EMP_NO = options.EMP_NO || '';
        this.S_ACC_NO = options.S_ACC_NO || '';
        this.V_ID = options.V_ID || '';
        this.SUMMARY_TYPE = options.SUMMARY_TYPE || '';
        this.SUMMARY_REPORT_TYPE = options.SUMMARY_REPORT_TYPE || '';
        this.SUMMARY_REPORT_DETAILS = options.SUMMARY_REPORT_DETAILS || '';
        this.IREPORT_TYPE = options.IREPORT_TYPE || '';
        this.GENERAL_REPORT_TYPE = options.GENERAL_REPORT_TYPE || '';
        this.COMPARISON_REPORT_TYPE = options.COMPARISON_REPORT_TYPE || '';
        this.IS_SHOW_YES = options.IS_SHOW_YES || '';
        this.IS_SHOW_NO = options.IS_SHOW_NO || '';
        this.IS_SHOW_TYPE = options.IS_SHOW_TYPE || '';
        this.CHEQUE = options.CHEQUE || '';
        this.BANK = options.BANK || '';
        this.REGESTER = options.REGESTER || '';
        this.PAY_TO_NAME = options.PAY_TO_NAME || '';

        this.REP_TYPE = options.REP_TYPE || '';
        this.REPORT_FORMAT_LIST = options.REPORT_FORMAT_LIST || '';

        this.SERVER_NAME = options.SERVER_NAME || '';
        this.MULTIPLE_CODE = options.MULTIPLE_CODE || '';        
        this.FORMAT_SHORT_NAME = options.FORMAT_SHORT_NAME || '';
        this.SS_CREATOR = options.SS_CREATOR || ''; //Prepared By
        this.CURRENCY_TYPE = options.CURRENCY_TYPE || '';
        this.SIDE_GROUP_LADER = options.SIDE_GROUP_LADER || '';
        this.SIDE_MOUNTH_STATE = options.SIDE_MOUNTH_STATE || '';
        this.POST_STATUS = options.POST_STATUS || '';
        this.COST_TYPE = options.COST_TYPE || '';
        this.CATEGORY = options.CATEGORY || '';
        this.SHOW_TYPE = options.SHOW_TYPE || '';
        this.QJ_NO = options.QJ_NO || '';
        this.DATE = options.DATE || '';
        this.IS_CATEGORY = options.IS_CATEGORY || '';
        this.PREPARED_BY = options.PREPARED_BY || '';
        this.CHECK_BY_NAME = options.CHECK_BY_NAME || '';
        this.REPORT_TYPE = options.REPORT_TYPE || '';
        this.MODULE = options.MODULE || '';
        this.TASK_NAME = options.TASK_NAME || '';
        this.TYPE_NAME = options.TYPE_NAME || '';
        this.APPSETDTL_NO = options.APPSETDTL_NO || null;
        
        this.REPORT_OPTION_ALL = options.REPORT_OPTION_ALL || '';
        this.REPORT_OPTION_ACTIVE = options.REPORT_OPTION_ACTIVE || '';
        this.REPORT_OPTION_INACTIVE = options.REPORT_OPTION_INACTIVE || '';
        this.REPORT_OPTION_REPORTXLS = options.REPORT_OPTION_REPORTXLS || '';

        this.IS_COST_CENTER_ALL = options.IS_COST_CENTER_ALL || false;
        this.OWN_REQUISITION_ONLY = options.OWN_REQUISITION_ONLY || false;
        this.ALL_REQ = options.ALL_REQ || false;
        this.IS_SHOW_DETAIL = options.IS_SHOW_DETAIL || false;
        this.IS_SHOW_PARTICULAR_QUS = options.IS_SHOW_PARTICULAR_QUS || false;
        this.IS_CHEQUE_DATE = options.IS_CHEQUE_DATE || false;
        this.IS_BUSINESS_AREA_ALL = options.IS_BUSINESS_AREA_ALL || false;
        this.CHECKED_ALL = options.CHECKED_ALL ||null;
        this.SHOW_DETAIL = options.SHOW_DETAIL || false;
        this.IS_SUPPRESS_ZERO = options.IS_SUPPRESS_ZERO || false;
        this.IS_REF_NO_ALL = options.IS_REF_NO_ALL || false;
        this.IS_OPENING = options.IS_OPENING || false;
        this.IS_SHOW_BUDGET = options.IS_SHOW_BUDGET || false;
        this.CTRL_SHOWPATH = options.CTRL_SHOWPATH || false;
        this.IS_SHOW_BALANCE = options.IS_SHOW_BALANCE || false;
        this.IS_SHOW_PAY = options.IS_SHOW_PAY || false;
        this.IS_SHOW_REC = options.IS_SHOW_REC || false;
        this.IS_SUMMARY_FLAG = options.IS_SUMMARY_FLAG || false;
        this.IS_CHECKED_ALL_COMPANY = options.IS_CHECKED_ALL_COMPANY || false;
        this.IS_GROUP_LEGERD_GROUP = options.IS_GROUP_LEGERD_GROUP || false;
        this.IS_GROUP_LEGERD_COMPANY_WISE = options.IS_GROUP_LEGERD_COMPANY_WISE || false;
        this.EXCLE = options.EXCLE || false;
        this.IS_COST_CENTER_INCOMPLETE = options.IS_COST_CENTER_INCOMPLETE || false;
        this.WATING = options.WATING || null;
        this.APPROVE = options.APPROVE || null;
        this.DENY = options.DENY || null;
        this.ACCEPT = options.ACCEPT || null;
        this.UNACCEPT = options.UNACCEPT || null;
        this.QJ_NO = options.QJ_NO || null;
        this.SEARCH_NAME = options.SEARCH_NAME || null;
        this.RECONCILED = options.RECONCILED || null;
        this.BUDGET_STATUS = options.BUDGET_STATUS || null;
        this.SUBMENU_ID = options.SUBMENU_ID || null;
        this.SUBMENU_ID2 = options.SUBMENU_ID2 || null;
        this.INVOICE = options.INVOICE || null;
        this.NEGOTIATION = options.NEGOTIATION || null;
        this.REALIZATION = options.REALIZATION || null;
        this.BILLDATE = options.BILLDATE || null;
        this.SUPPLIER_NOT_MAP = options.SUPPLIER_NOT_MAP ||null;
        this.SELECTED = options.SELECTED || null;
        this.CUSTOMER_NOT_MAP = options.CUSTOMER_NOT_MAP ||null;
        this.STATUS = options.STATUS ||null;
        this.FORM_ID = options.FORM_ID || null;
        this.CUSTOMER_NAME = options.CUSTOMER_NAME || null;
        this.CUSTOMER_NO = options.CUSTOMER_NO || null;
        this.LC_NO = options.LC_NO || null;
        this.SALESCONTRACT_NO = options.SALESCONTRACT_NO || null;
        this.SUPPLIER_NO = options.SUPPLIER_NO ||null;
        this.PAY_NO = options.PAY_NO ||null;
        this.PAY_ID = options.PAY_ID ||null;
        this.MONEYPAY_NO = options.MONEYPAY_NO || null;
        this.TRN_LIST = options.TRN_LIST || null;
    }
}
